sonar.projectKey=StudyConnectGroup2
sonar.projectName=StudyConnectGroup2
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test,src

sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,**/test/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

