sonar.projectKey=StudyConnectGroup2
sonar.projectName=StudyConnectGroup2
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test

sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts,src/**/*.e2e-spec.ts,test/**/*.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**